In [ ]:
# Case Study - NLP

In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('punkt')
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# 1.a) Create a function named ‘tokenized_text ()’that takes ‘sentence’ as its argument and performs
# word tokenization and removes all stopwords

In [ ]:
stop_words = set(stopwords.words("english"))

In [ ]:
def tokenizedText(sentences1):
  sentence = nltk.word_tokenize(sentences1)
  #print("Sentences  :", sentences1)
  #print("\n sentence  :", sentence)
  cleanedText = [w.lower() for w in sentence if w not in stop_words]

  return cleanedText

In [ ]:
# 1.b) Create a function named ‘sorted_token ()’ that takes ‘sentence’ as its argument and removes
# the duplicate word tokens and returns a sorted list of word tokens

In [ ]:
def sortedToken(sentence2):
  wordTokens = []
 
  for sent in sentence2:
    wordList = tokenizedText(sent)
    wordTokens.extend(wordList)
    # print(wordList)
    # print("sortedToken  :",wordTokens)

  wordTokens = sorted(list(set(wordTokens)))
  print("sortedTokens  :",wordTokens)
  
  return wordTokens

In [ ]:
sentenceList = ["John likes to watch movies",
                "Mary likes to play football",
                "John likes to watch football games but does not like to play football",
                "Both John and Mary like to play video games"]
sentences1 = "John likes to watch football games but does not like to play football"
text1 = sortedToken(sentenceList)
print("Cleaned Text : ",text1)

Sentences  : John likes to watch movies

 sentence  : ['John', 'likes', 'to', 'watch', 'movies']
Sentences  : Mary likes to play football

 sentence  : ['Mary', 'likes', 'to', 'play', 'football']
Sentences  : John likes to watch football games but does not like to play football

 sentence  : ['John', 'likes', 'to', 'watch', 'football', 'games', 'but', 'does', 'not', 'like', 'to', 'play', 'football']
Sentences  : Both John and Mary like to play video games

 sentence  : ['Both', 'John', 'and', 'Mary', 'like', 'to', 'play', 'video', 'games']
sortedToken 1 : ['both', 'football', 'games', 'john', 'like', 'likes', 'mary', 'movies', 'play', 'video', 'watch']
Cleaned Text :  ['both', 'football', 'games', 'john', 'like', 'likes', 'mary', 'movies', 'play', 'video', 'watch']


In [ ]:
# 1.c) Create a function named ‘bag_of_word ()’ that takes ‘sentence’ and ‘word’ as its arguments,
# calculates the frequency word count of word tokens, and returns a NumPy array of word tokens

In [ ]:
def bagofWords(sentence1, words1): 
  wordsList = tokenizedText(sentence1)
  #print(type(wordsList))
  print("words list :",wordsList, "\n Vocubulary/SortedToken :",words1)
  wordBag = np.zeros(len(words1))
  for w in wordsList:
    for j, word in enumerate(words1):
      if w == word:
        wordBag[j] += 1
  
  return np.array(wordBag)

In [ ]:
# 1.d) Create a bag-of-words model on the following sentences using the three functions defined above:
# Joe went to the store
# Joe wants to buy a dining set
# Joe met John at the store
# Joe and John are best friends

In [ ]:
sentenceList1 = ["Joe went to the store",
                  "Joe wants to buy a dining set",
                  "Joe met John at the store",
                  "Joe and John are best friends"]
                  

In [ ]:
sentences1 = "John likes to watch football games but does not like to play football"
vocu = sortedToken(sentenceList1)
#print("Cleaned Text : ",text1)
bag = bagofWords(sentences1,vocu)
print("Bag of words array : ",bag)

sortedToken  : ['best', 'buy', 'dining', 'friends', 'joe', 'john', 'met', 'set', 'store', 'wants', 'went']
words list : ['john', 'likes', 'watch', 'football', 'games', 'like', 'play', 'football'] 
 Vocubulary/SortedToken : ['best', 'buy', 'dining', 'friends', 'joe', 'john', 'met', 'set', 'store', 'wants', 'went']
Bag of words array :  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Assignment for CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# 2.b) Create a numpy array named ‘corpus’ that contains the following sentences:

In [ ]:
corpus = ["Joe went to the store",
          "Joe wants to buy a dining set",
          "Joe met John at the store",
          "Joe and John are best friends"]
corpus = np.array(corpus)
corpus

array(['Joe went to the store', 'Joe wants to buy a dining set',
       'Joe met John at the store', 'Joe and John are best friends'],
      dtype='<U29')

In [ ]:
# 2.c) Use the ‘CountVectorizer’ class object to fit and transform the text present in ‘corpus’ and
# store the result in ‘bag_of_words’

In [ ]:
countVector = CountVectorizer(stop_words=stop_words)

bagofWords = countVector.fit_transform(corpus)

In [ ]:
# 2.d) Print ‘bag_of_words’ as a numpy array

bagofWords = bagofWords.toarray()

print("Bag of Words :", bagofWords)


Bag of Words : [[0 0 0 0 1 0 0 0 1 0 1]
 [0 1 1 0 1 0 0 1 0 1 0]
 [0 0 0 0 1 1 1 0 1 0 0]
 [1 0 0 1 1 1 0 0 0 0 0]]


In [ ]:
# 2.e) Print all feature names of the above-created ‘CountVectorizer’ object

featureNames = countVector.get_feature_names()

print("Feature Names :", featureNames)

Feature Names : ['best', 'buy', 'dining', 'friends', 'joe', 'john', 'met', 'set', 'store', 'wants', 'went']


In [ ]:
# 2.f) Print the ‘bag_of_words’ array as a Pandas Data Frame with column names as feature names

pd.DataFrame(bagofWords, columns = featureNames)


best  buy  dining  friends  joe  john  met  set  store  wants  went
0     0    0       0        0    1     0    0    0      1      0     1
1     0    1       1        0    1     0    0    1      0      1     0
2     0    0       0        0    1     1    1    0      1      0     0
3     1    0       0        1    1     1    0    0      0      0     0

In [ ]:
# 3. Assignment for Term Frequency–Inverse Document Frequency

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# 3.b) Create a numpy array named ‘corpus’ that contains the following sentences:
# Joe went to the store, Joe wants to buy a dining set, Joe met John at the store, Joe and John are best friends

corpus = ["Joe went to the store", 
           "Joe wants to buy a dining set", 
           "Joe met John at the store", 
           "Joe and John are best friends"]
corpus3 = np.array(corpus)
corpus3

array(['Joe went to the store', 'Joe wants to buy a dining set',
       'Joe met John at the store', 'Joe and John are best friends'],
      dtype='<U29')

In [ ]:
# 3.c) Use the ‘TfidfVectorizer’ class to create an object to fit and transform the text present in
# ‘corpus’ created above and store the result in ‘bag_of_words’

tfIDVector = TfidfVectorizer(stop_words = stop_words)

bagofWords3 = tfIDVector.fit_transform(corpus3)

In [ ]:
# 3.d) Print ‘bag_of_words’ as a numpy array

bagofWords3 = bagofWords3.toarray()

print("Bag of Words :", bagofWords3)

Bag of Words : [[0.         0.         0.         0.         0.37919167 0.
  0.         0.         0.5728925  0.         0.72664149]
 [0.         0.48380259 0.48380259 0.         0.25246826 0.
  0.         0.48380259 0.         0.48380259 0.        ]
 [0.         0.         0.         0.         0.32902288 0.4970962
  0.6305035  0.         0.4970962  0.         0.        ]
 [0.58783765 0.         0.         0.58783765 0.30675807 0.46345796
  0.         0.         0.         0.         0.        ]]


In [ ]:
# 3.e) Print all feature names of the above-created ‘TfidfVectorizer’ object

featureNames3 = tfIDVector.get_feature_names()

print("Feature Names :", featureNames3)

Feature Names : ['best', 'buy', 'dining', 'friends', 'joe', 'john', 'met', 'set', 'store', 'wants', 'went']


In [ ]:
# 3.f) Print the ‘bag_of_words’ array as a pandas data frame with column names as feature names

pd.DataFrame(bagofWords3, columns = featureNames3)

best       buy    dining  ...     store     wants      went
0  0.000000  0.000000  0.000000  ...  0.572892  0.000000  0.726641
1  0.000000  0.483803  0.483803  ...  0.000000  0.483803  0.000000
2  0.000000  0.000000  0.000000  ...  0.497096  0.000000  0.000000
3  0.587838  0.000000  0.000000  ...  0.000000  0.000000  0.000000

[4 rows x 11 columns]