In [ ]:
# 1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
# Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
# [ [5, 5, 5], [5, 5, 5], [5, 5, 5] ]

In [ ]:
import numpy as np

In [ ]:
def DimFunction(t, a):
    print(t[0], t[1])
    print(a)
    arr = np.full((t[0],t[1]),a)
    return arr

In [ ]:
 tuple1 = (5,5)
 b = 10
 array1 = DimFunction(tuple1,b)
 array1

5 5
10


array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
# 2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [ ]:
def sumMethod(params):
     list1 = []
     count = 0
     length1 = len(params)
     temp = params[count].ndim
     while (count  < length1):
       dim = params[count].ndim
       if (temp == dim):
          list1.append(params[count])
       count +=1
       temp = dim
       
     print("Size of the list  = ",len(list1))
     sum1 = np.sum(list1)
     return sum1

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[10,12,13],[14,15,16]])
array3 = np.array([[2,4,6],[8,10,12]])
array4 = np.array([5,10,15])

param = np.array([array1,array2,array3, array4])
sumValue = sumMethod(param)
print("Total Sum Value = ", sumValue) 

Size of the list  =  3
Total Sum Value =  143


In [ ]:
# 3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. 
# The method should return the top-left N X M sub matrix

In [ ]:
def subMatrix(arr, n ,m):
    array1 = arr[:n-1,:m-1]
    print(array1)
    return array1

In [ ]:
sample = np.array([[1,2,5],[4,5,6],[7,8,9],[10,11,12]])
print("Sample matrix dimension =",sample.ndim, "\nSample shape =",sample.shape[0])
ret = subMatrix(sample,sample.shape[0], sample.shape[1])

Sample matrix dimension = 2 
Sample shape = 4
[[1 2]
 [4 5]
 [7 8]]


In [ ]:
# 4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M.
# The method should return the bottom-right N X M sub matrix e.g.:

In [ ]:
def twoDArray(arr,n, m):
  print("In side function :\n",arr)
  array1 = arr[n-2:,m-2:]
  return array1

In [ ]:
sample2 = np.array([[1,2,5],[4,5,6],[7,8,9],[10,11,12]])
print("Sample2 matrix dimension =",sample2.ndim, "\nSample2 shape =",sample2.shape[0])
retArray = twoDArray(sample2,sample2.shape[0], sample2.shape[1])
print("\n Bottom right N x M sub matrix  :\n",retArray)

Sample2 matrix dimension = 2 
Sample2 shape = 4
In side function :
 [[ 1  2  5]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Bottom right N x M sub matrix  :
 [[ 8  9]
 [11 12]]


In [ ]:
# 5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. 
# The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:

In [ ]:
def oneDArray(arr):
   mean = arr.mean()
   std_dev = arr.std()
   dict = {'mean': mean,'std_dev':std_dev}
   return dict

In [ ]:
sampleArray = np.array([1,2,5])
returnDic = oneDArray(sampleArray)
print("Returned Dictionary :\n ",returnDic)

Returned Dictionary :
  {'mean': 2.6666666666666665, 'std_dev': 1.699673171197595}
